---
title: "Project Code"
subtitle: JAM Team
author: Grace Gormley, Alexa Pryor, Jenna Krinsky
date: 12/09/2025
number-sections: true
abstract: _This file contains the code for the project on <>, as part of the STAT303-1-Sec20&21 course in Fall 2024_.
format: 
  html:
    toc: true
    toc-title: Contents
    self-contained: true
    font-size: 100%
    toc-depth: 4
    mainfont: serif
jupyter: python3
---

## Importing Packages and Configuring

In [50]:
import pandas as pd
import numpy as np

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# Configure matplotlib for better display in Jupyter
%matplotlib inline

# Set default figure size for all plots (width, height in inches)
import matplotlib
matplotlib.rcParams['figure.figsize'] = (8, 5)  # Larger default size
matplotlib.rcParams['figure.dpi'] = 100          # Resolution
matplotlib.rcParams['font.size'] = 11            # Default font size

# Configure Seaborn style
sns.set_style("whitegrid")                       # Clean grid background
sns.set_palette("deep")                          # Colorblind-friendly palette
sns.set_context("notebook")                      # Appropriate scaling

## Data quality check / cleaning / preparation 

Put code with comments. The comments should explain the code such that it can be easily understood. You may put text *(in a markdown cell)* before a large chunk of code to explain the overall purpose of the code, if it is not intuitive. **Put the name of the person / persons who contributed to each code chunk / set of code chunks.** An example is given below.

### Exploring Initial Data
*By Grace Gormley*

In [51]:
#Making my divvy dataset from 2024-2025
import glob #gonna be honest, I got this from chat so I dont need to do it one by one

files = glob.glob("/Users/gracegormley/Desktop/Stat 303-1/project/divvy 2024-2025/*.csv")   # grabs all CSVs in the folder

dfs = []                                      # empty list to store DataFrames
for f in files:
    dfs.append(pd.read_csv(f))

divvy = pd.concat(dfs, ignore_index=True)

In [52]:
#make sure they're in chronological order
divvy["started_at"] = pd.to_datetime(divvy["started_at"], format="mixed")
divvy = divvy.sort_values(by="started_at")

In [53]:
#Importing my extra datasets
traffic = pd.read_csv('/Users/gracegormley/Desktop/Stat 303-1/project/Chicago_Traffic_Tracker_-_Congestion_Estimates_by_Segments_20251125.csv')
CTA_riders = pd.read_csv('/Users/gracegormley/Desktop/Stat 303-1/project/CTA_-_Ridership_-_Daily_Boarding_Totals_20251125.csv')
bus_stops = pd.read_csv('/Users/gracegormley/Desktop/Stat 303-1/project/CTA_BusStops_20251125.csv')
L_stops = pd.read_csv('/Users/gracegormley/Desktop/Stat 303-1/project/CTA_-_System_Information_-_List_of_\'L\'_Stops_20251125.csv')
population = pd.read_csv('/Users/gracegormley/Desktop/Stat 303-1/project/Chicago_Population_Counts_20251125.csv')

In [54]:
#Printing the head of each dataset to get an idea of the contents

In [55]:
divvy.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
3486147,6A9D809ABDF70617,electric_bike,2024-01-01 00:00:39,2024-01-01 00:07:56,NaN,NaN,Clark St & Wrightwood Ave,TA1305000014,41.950000,-87.650000,41.929546,-87.643118,member
3491360,26B9F6E416A68EBA,electric_bike,2024-01-01 00:00:50,2024-01-01 00:04:20,NaN,NaN,NaN,NaN,41.900000,-87.620000,41.900000,-87.620000,casual
3486040,30EF016A0DF5ECEE,electric_bike,2024-01-01 00:00:52,2024-01-01 00:04:25,NaN,NaN,NaN,NaN,41.900000,-87.620000,41.900000,-87.620000,casual
3467452,0D9E85F804C85828,electric_bike,2024-01-01 00:00:53,2024-01-01 00:22:30,Clinton St & Madison St,TA1305000032,NaN,NaN,41.881909,-87.641296,41.890000,-87.620000,member
3410785,56F5C3ED5178C131,classic_bike,2024-01-01 00:01:01,2024-01-01 00:24:12,LaSalle St & Illinois St,13430,Indiana Ave & Roosevelt Rd,SL-005,41.890762,-87.631697,41.867888,-87.623041,member

In [56]:
traffic.head()

,SEGMENTID,STREET,DIRECTION,FROM_STREET,TO_STREET,LENGTH,STREET_HEADING,COMMENTS,START_LONGITUDE,START_LATITUDE,END_LONGITUDE,END_LATITUDE,CURRENT_SPEED,LAST_UPDATED
0,1284,Chicago,WB,Lake Shore Dr,Michigan,0.370000,E,NaN,-87.617048,41.896936,-87.624241,41.896835,-1,2011-08-10 00:00:00.0
1,951,Washington,WB,Kedzie,Schraeder,0.280000,W,NaN,-87.706169,41.882932,-87.711747,41.882818,-1,2010-07-21 14:51:00.0
2,750,Elston,SE,Milwaukee,Austin,0.330000,N,NaN,-87.783224,41.992665,-87.778073,41.989905,-1,2010-07-21 14:51:10.0
3,1164,Harlem,SB,Ogden,Pershing,0.173023,S,Outside City Limits,-87.802922,41.823751,-87.803025,41.821245,-1,2010-07-21 14:51:15.0
4,1122,127th,EB,Western,I-57 Expy,0.907892,W,Outside City Limits,-87.680077,41.662512,-87.662540,41.662850,-1,2010-07-21 14:51:06.0

In [57]:
CTA_riders.head()

  service_date day_type      bus rail_boardings total_rides
0   01/01/2001        U  297,192        126,455     423,647
1   01/02/2001        W  780,827        501,952   1,282,779
2   01/03/2001        W  824,923        536,432   1,361,355
3   01/04/2001        W  870,021        550,011   1,420,032
4   01/05/2001        W  890,426        557,917   1,448,343

In [58]:
bus_stops.head()

,the_geom,SYSTEMSTOP,STREET,CROSS_ST,DIR,POS,ROUTESSTPG,OWLROUTES,CITY,PUBLIC_NAM
0,POINT (-87.74750923800002 41.956892084),"15,189",CICERO,BERTEAU (north leg),SB,FS,"54,54A",NaN,CHICAGO,Cicero & Berteau
1,POINT (-87.64178572600002 41.67799153599998),"14,545",HALSTED,119TH STREET,NB,FS,"8A,108",NaN,CHICAGO,Halsted & 119th Street
2,POINT (-87.70896851700002 42.012049691000016),"15,046",KEDZIE,TOUHY,NB,FS,11,NaN,CHICAGO,Kedzie & Touhy
3,POINT (-87.66891603599998 41.954186386),"6,280",ASHLAND,IRVING PARK,NB,NS,"9,X9",NaN,CHICAGO,Ashland & Irving Park
4,POINT (-87.67517869800002 41.83201446999999),"4,484",ARCHER,DAMEN,SWB,NS,62,N62,CHICAGO,Archer & Damen

In [59]:
L_stops.head()

,STOP_ID,DIRECTION_ID,STOP_NAME,STATION_NAME,STATION_DESCRIPTIVE_NAME,MAP_ID,ADA,RED,BLUE,G,BRN,P,Y,Pnk,O,Location
0,30162,W,18th (54th/Cermak-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,True,False,"(41.857908, -87.669147)"
1,30161,E,18th (Loop-bound),18th,18th (Pink Line),40830,True,False,False,False,False,False,False,True,False,"(41.857908, -87.669147)"
2,30022,N,35th/Archer (Loop-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,True,"(41.829353, -87.680622)"
3,30023,S,35th/Archer (Midway-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,False,False,False,False,True,"(41.829353, -87.680622)"
4,30213,N,35-Bronzeville-IIT (Harlem-bound),35th-Bronzeville-IIT,35th-Bronzeville-IIT (Green Line),41120,True,False,False,True,False,False,False,False,False,"(41.831677, -87.625826)"

In [60]:
population.head()

,Geography Type,Year,Geography,Population - Total,Population - Age 0-17,Population - Age 18-29,Population - Age 30-39,Population - Age 40-49,Population - Age 50-59,Population - Age 60-69,...,Population - Age 18+,Population - Age 65+,Population - Female,Population - Male,Population - Latinx,Population - Asian Non-Latinx,Population - Black Non-Latinx,Population - White Non-Latinx,Population - Other Race Non-Latinx,Record ID
0,Citywide,2018,Chicago,"2,705,988","548,999","552,935","456,321","336,457","312,965","262,991",...,"2,156,989","349,712","1,386,113","1,319,875","776,661","179,841","784,266","899,980","119,467",Citywide-Chicago-2018
1,ZIP Code,2018,60601,"14,675",820,"4,606","2,792","2,190","1,333","1,340",...,"13,855","2,075","7,484","7,191","1,274",NaN,NaN,"9,677",NaN,ZIP_Code-60601-2018
2,ZIP Code,2018,60602,"1,244",149,435,462,135,53,10,...,"1,095",5,551,693,81,NaN,NaN,788,NaN,ZIP_Code-60602-2018
3,ZIP Code,2018,60603,"1,174",56,561,101,97,197,97,...,"1,118",112,601,573,115,NaN,NaN,707,NaN,ZIP_Code-60603-2018
4,ZIP Code,2018,60604,782,38,303,104,51,101,130,...,744,93,413,369,34,NaN,NaN,479,NaN,ZIP_Code-60604-2018

In [61]:
#Looking at missing data

In [62]:
divvy.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    2155418
start_station_id      2155418
end_station_name      2236017
end_station_id        2236017
start_lat                   0
start_lng                   0
end_lat                 12288
end_lng                 12288
member_casual               0
dtype: int64

In [63]:
traffic.isnull().sum()

SEGMENTID             0
STREET                0
DIRECTION             0
FROM_STREET           0
TO_STREET             0
LENGTH                0
 STREET_HEADING       0
 COMMENTS          1032
START_LONGITUDE       0
 START_LATITUDE       0
END_LONGITUDE         0
 END_LATITUDE         0
 CURRENT_SPEED        0
 LAST_UPDATED         0
dtype: int64

In [64]:
CTA_riders.isnull().sum()

service_date      0
day_type          0
bus               0
rail_boardings    0
total_rides       0
dtype: int64

In [65]:
bus_stops.isnull().sum()

the_geom         0
SYSTEMSTOP       0
STREET           0
CROSS_ST         0
DIR              0
POS              0
ROUTESSTPG       4
OWLROUTES     8602
CITY             1
PUBLIC_NAM       0
dtype: int64

In [66]:
L_stops.isnull().sum()

STOP_ID                     0
DIRECTION_ID                0
STOP_NAME                   0
STATION_NAME                0
STATION_DESCRIPTIVE_NAME    0
MAP_ID                      0
ADA                         0
RED                         0
BLUE                        0
G                           0
BRN                         0
P                           0
Y                           0
Pnk                         0
O                           0
Location                    0
dtype: int64

In [67]:
population.isnull().sum()

Geography Type                         0
Year                                   0
Geography                              0
Population - Total                     0
Population - Age 0-17                  0
Population - Age 18-29                 0
Population - Age 30-39                 0
Population - Age 40-49                 0
Population - Age 50-59                 0
Population - Age 60-69                 0
Population - Age 70-79                 0
Population - Age 80+                   0
Population - Age 0-4                   0
Population - Age 5-11                 59
Population - Age 12-17                59
Population - Age 5+                    0
Population - Age 18+                   0
Population - Age 65+                   0
Population - Female                    0
Population - Male                      0
Population - Latinx                    0
Population - Asian Non-Latinx         59
Population - Black Non-Latinx         59
Population - White Non-Latinx          0
Population - Other Race Non-Latinx    59
Record ID                              0
dtype: int64

In [68]:
#...Plot for distribution of variables...#

### Data cleaning
*By Sankaranarayanan Balasubramanian & Fiona Fe*

In [69]:
#...Code with comments...#

# Imputing missing values #

### Data preparation
*By Ryu Kimiko*

In [70]:
######---------------Creating new variables----------------#########

#Creating number of bedrooms per unit floor area

#Creating ratio of bathrooms to bedrooms

#Creating ratio of carpet area to floor area

In [71]:
######-----Standardizing the dataset ----------------------#########

## Exploratory data analysis

Put code with comments. The comments should explain the code such that it can be easily understood. You may put text *(in a markdown cell)* before a large chunk of code to explain the overall purpose of the code, if it is not intuitive. **Put the name of the person / persons who contributed to each code chunk / set of code chunks.**

### Analysis 1
*By \<Name of person doing the analysis>*

### Analysis 2
*By \<Name of person doing the analysis>*

### Analysis 3
*By \<Name of person doing the analysis>*

### Analysis 4
*By \<Name of person doing the analysis>*

## Other sections

Put code with comments. The comments should explain the code such that it can be easily understood. You may put text *(in a markdown cell)* before a large chunk of code to explain the overall purpose of the code, if it is not intuitive. **Put the name of the person / persons who contributed to each code chunk / set of code chunks.**

Put each model in a section of its name and mention the name of the team-member tuning the model. Below is an example:

## Conclusions and Recommendations to stakeholder(s)

You may or may not have code to put in this section. Delete this section if it is irrelevant.